// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package org.osv.eventdb;

public final class OperatorLibrary {
  private OperatorLibrary() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OperatorLibraryRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string column = 1;
    /**
     * <code>required string column = 1;</code>
     *
     * <pre>
     *列限定符
     * </pre>
     */
    boolean hasColumn();
    /**
     * <code>required string column = 1;</code>
     *
     * <pre>
     *列限定符
     * </pre>
     */
    java.lang.String getColumn();
    /**
     * <code>required string column = 1;</code>
     *
     * <pre>
     *列限定符
     * </pre>
     */
    com.google.protobuf.ByteString
        getColumnBytes();
  }
  /**
   * Protobuf type {@code OperatorLibraryRequest}
   *
   * <pre>
   * 定义请求包
   * </pre>
   */
  public static final class OperatorLibraryRequest extends
      com.google.protobuf.GeneratedMessage
      implements OperatorLibraryRequestOrBuilder {
    // Use OperatorLibraryRequest.newBuilder() to construct.
    private OperatorLibraryRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OperatorLibraryRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OperatorLibraryRequest defaultInstance;
    public static OperatorLibraryRequest getDefaultInstance() {
      return defaultInstance;
    }

    public OperatorLibraryRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OperatorLibraryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              column_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.osv.eventdb.OperatorLibrary.internal_static_OperatorLibraryRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.osv.eventdb.OperatorLibrary.internal_static_OperatorLibraryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.class, org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<OperatorLibraryRequest> PARSER =
        new com.google.protobuf.AbstractParser<OperatorLibraryRequest>() {
      public OperatorLibraryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OperatorLibraryRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OperatorLibraryRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string column = 1;
    public static final int COLUMN_FIELD_NUMBER = 1;
    private java.lang.Object column_;
    /**
     * <code>required string column = 1;</code>
     *
     * <pre>
     *列限定符
     * </pre>
     */
    public boolean hasColumn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string column = 1;</code>
     *
     * <pre>
     *列限定符
     * </pre>
     */
    public java.lang.String getColumn() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          column_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string column = 1;</code>
     *
     * <pre>
     *列限定符
     * </pre>
     */
    public com.google.protobuf.ByteString
        getColumnBytes() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        column_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      column_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasColumn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getColumnBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getColumnBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OperatorLibraryRequest}
     *
     * <pre>
     * 定义请求包
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.osv.eventdb.OperatorLibrary.OperatorLibraryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.osv.eventdb.OperatorLibrary.internal_static_OperatorLibraryRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.osv.eventdb.OperatorLibrary.internal_static_OperatorLibraryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.class, org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.Builder.class);
      }

      // Construct using org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        column_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.osv.eventdb.OperatorLibrary.internal_static_OperatorLibraryRequest_descriptor;
      }

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest getDefaultInstanceForType() {
        return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
      }

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest build() {
        org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest buildPartial() {
        org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest result = new org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.column_ = column_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest) {
          return mergeFrom((org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest other) {
        if (other == org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance()) return this;
        if (other.hasColumn()) {
          bitField0_ |= 0x00000001;
          column_ = other.column_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasColumn()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string column = 1;
      private java.lang.Object column_ = "";
      /**
       * <code>required string column = 1;</code>
       *
       * <pre>
       *列限定符
       * </pre>
       */
      public boolean hasColumn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string column = 1;</code>
       *
       * <pre>
       *列限定符
       * </pre>
       */
      public java.lang.String getColumn() {
        java.lang.Object ref = column_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          column_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string column = 1;</code>
       *
       * <pre>
       *列限定符
       * </pre>
       */
      public com.google.protobuf.ByteString
          getColumnBytes() {
        java.lang.Object ref = column_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          column_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string column = 1;</code>
       *
       * <pre>
       *列限定符
       * </pre>
       */
      public Builder setColumn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 1;</code>
       *
       * <pre>
       *列限定符
       * </pre>
       */
      public Builder clearColumn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        column_ = getDefaultInstance().getColumn();
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 1;</code>
       *
       * <pre>
       *列限定符
       * </pre>
       */
      public Builder setColumnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        column_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OperatorLibraryRequest)
    }

    static {
      defaultInstance = new OperatorLibraryRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OperatorLibraryRequest)
  }

  public interface OperatorLibraryResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated double result = 1;
    /**
     * <code>repeated double result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    java.util.List<java.lang.Double> getResultList();
    /**
     * <code>repeated double result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    int getResultCount();
    /**
     * <code>repeated double result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    double getResult(int index);
  }
  /**
   * Protobuf type {@code OperatorLibraryResponse}
   *
   * <pre>
   * 定义回复包
   * </pre>
   */
  public static final class OperatorLibraryResponse extends
      com.google.protobuf.GeneratedMessage
      implements OperatorLibraryResponseOrBuilder {
    // Use OperatorLibraryResponse.newBuilder() to construct.
    private OperatorLibraryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OperatorLibraryResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OperatorLibraryResponse defaultInstance;
    public static OperatorLibraryResponse getDefaultInstance() {
      return defaultInstance;
    }

    public OperatorLibraryResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OperatorLibraryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                result_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              result_.add(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                result_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                result_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.osv.eventdb.OperatorLibrary.internal_static_OperatorLibraryResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.osv.eventdb.OperatorLibrary.internal_static_OperatorLibraryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.class, org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<OperatorLibraryResponse> PARSER =
        new com.google.protobuf.AbstractParser<OperatorLibraryResponse>() {
      public OperatorLibraryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OperatorLibraryResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OperatorLibraryResponse> getParserForType() {
      return PARSER;
    }

    // repeated double result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Double> result_;
    /**
     * <code>repeated double result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    public java.util.List<java.lang.Double>
        getResultList() {
      return result_;
    }
    /**
     * <code>repeated double result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated double result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    public double getResult(int index) {
      return result_.get(index);
    }

    private void initFields() {
      result_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < result_.size(); i++) {
        output.writeDouble(1, result_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getResultList().size();
        size += dataSize;
        size += 1 * getResultList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OperatorLibraryResponse}
     *
     * <pre>
     * 定义回复包
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.osv.eventdb.OperatorLibrary.OperatorLibraryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.osv.eventdb.OperatorLibrary.internal_static_OperatorLibraryResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.osv.eventdb.OperatorLibrary.internal_static_OperatorLibraryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.class, org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.Builder.class);
      }

      // Construct using org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.osv.eventdb.OperatorLibrary.internal_static_OperatorLibraryResponse_descriptor;
      }

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getDefaultInstanceForType() {
        return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
      }

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse build() {
        org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse buildPartial() {
        org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse result = new org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.result_ = result_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse) {
          return mergeFrom((org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse other) {
        if (other == org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance()) return this;
        if (!other.result_.isEmpty()) {
          if (result_.isEmpty()) {
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultIsMutable();
            result_.addAll(other.result_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated double result = 1;
      private java.util.List<java.lang.Double> result_ = java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = new java.util.ArrayList<java.lang.Double>(result_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public java.util.List<java.lang.Double>
          getResultList() {
        return java.util.Collections.unmodifiableList(result_);
      }
      /**
       * <code>repeated double result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public int getResultCount() {
        return result_.size();
      }
      /**
       * <code>repeated double result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public double getResult(int index) {
        return result_.get(index);
      }
      /**
       * <code>repeated double result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public Builder setResult(
          int index, double value) {
        ensureResultIsMutable();
        result_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public Builder addResult(double value) {
        ensureResultIsMutable();
        result_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureResultIsMutable();
        super.addAll(values, result_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public Builder clearResult() {
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OperatorLibraryResponse)
    }

    static {
      defaultInstance = new OperatorLibraryResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OperatorLibraryResponse)
  }

  /**
   * Protobuf service {@code OperatorLibraryService}
   *
   * <pre>
   * 定义RPC服务
   * </pre>
   */
  public static abstract class OperatorLibraryService
      implements com.google.protobuf.Service {
    protected OperatorLibraryService() {}

    public interface Interface {
      /**
       * <code>rpc getGamma(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
       *
       * <pre>
       *获取求和结果
       * </pre>
       */
      public abstract void getGamma(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

      /**
       * <code>rpc getErf(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
       */
      public abstract void getErf(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

      /**
       * <code>rpc getSum(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
       */
      public abstract void getSum(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

      /**
       * <code>rpc getAve(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
       */
      public abstract void getAve(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

      /**
       * <code>rpc getMax(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
       */
      public abstract void getMax(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

      /**
       * <code>rpc getMin(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
       */
      public abstract void getMin(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new OperatorLibraryService() {
        @java.lang.Override
        public  void getGamma(
            com.google.protobuf.RpcController controller,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
            com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
          impl.getGamma(controller, request, done);
        }

        @java.lang.Override
        public  void getErf(
            com.google.protobuf.RpcController controller,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
            com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
          impl.getErf(controller, request, done);
        }

        @java.lang.Override
        public  void getSum(
            com.google.protobuf.RpcController controller,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
            com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
          impl.getSum(controller, request, done);
        }

        @java.lang.Override
        public  void getAve(
            com.google.protobuf.RpcController controller,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
            com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
          impl.getAve(controller, request, done);
        }

        @java.lang.Override
        public  void getMax(
            com.google.protobuf.RpcController controller,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
            com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
          impl.getMax(controller, request, done);
        }

        @java.lang.Override
        public  void getMin(
            com.google.protobuf.RpcController controller,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
            com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
          impl.getMin(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getGamma(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request);
            case 1:
              return impl.getErf(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request);
            case 2:
              return impl.getSum(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request);
            case 3:
              return impl.getAve(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request);
            case 4:
              return impl.getMax(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request);
            case 5:
              return impl.getMin(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
            case 1:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
            case 2:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
            case 3:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
            case 4:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
            case 5:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
            case 1:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
            case 2:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
            case 3:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
            case 4:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
            case 5:
              return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getGamma(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
     *
     * <pre>
     *获取求和结果
     * </pre>
     */
    public abstract void getGamma(
        com.google.protobuf.RpcController controller,
        org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
        com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

    /**
     * <code>rpc getErf(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
     */
    public abstract void getErf(
        com.google.protobuf.RpcController controller,
        org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
        com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

    /**
     * <code>rpc getSum(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
     */
    public abstract void getSum(
        com.google.protobuf.RpcController controller,
        org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
        com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

    /**
     * <code>rpc getAve(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
     */
    public abstract void getAve(
        com.google.protobuf.RpcController controller,
        org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
        com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

    /**
     * <code>rpc getMax(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
     */
    public abstract void getMax(
        com.google.protobuf.RpcController controller,
        org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
        com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

    /**
     * <code>rpc getMin(.OperatorLibraryRequest) returns (.OperatorLibraryResponse);</code>
     */
    public abstract void getMin(
        com.google.protobuf.RpcController controller,
        org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
        com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.osv.eventdb.OperatorLibrary.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getGamma(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request,
            com.google.protobuf.RpcUtil.<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse>specializeCallback(
              done));
          return;
        case 1:
          this.getErf(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request,
            com.google.protobuf.RpcUtil.<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse>specializeCallback(
              done));
          return;
        case 2:
          this.getSum(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request,
            com.google.protobuf.RpcUtil.<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse>specializeCallback(
              done));
          return;
        case 3:
          this.getAve(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request,
            com.google.protobuf.RpcUtil.<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse>specializeCallback(
              done));
          return;
        case 4:
          this.getMax(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request,
            com.google.protobuf.RpcUtil.<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse>specializeCallback(
              done));
          return;
        case 5:
          this.getMin(controller, (org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest)request,
            com.google.protobuf.RpcUtil.<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
        case 1:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
        case 2:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
        case 3:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
        case 4:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
        case 5:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
        case 1:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
        case 2:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
        case 3:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
        case 4:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
        case 5:
          return org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.osv.eventdb.OperatorLibrary.OperatorLibraryService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getGamma(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.class,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance()));
      }

      public  void getErf(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.class,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance()));
      }

      public  void getSum(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.class,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance()));
      }

      public  void getAve(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.class,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance()));
      }

      public  void getMax(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(4),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.class,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance()));
      }

      public  void getMin(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request,
          com.google.protobuf.RpcCallback<org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(5),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.class,
            org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getGamma(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException;

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getErf(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException;

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getSum(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException;

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getAve(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException;

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getMax(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException;

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getMin(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getGamma(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance());
      }


      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getErf(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance());
      }


      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getSum(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance());
      }


      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getAve(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance());
      }


      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getMax(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(4),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance());
      }


      public org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse getMin(
          com.google.protobuf.RpcController controller,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(5),
          controller,
          request,
          org.osv.eventdb.OperatorLibrary.OperatorLibraryResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:OperatorLibraryService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OperatorLibraryRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OperatorLibraryRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OperatorLibraryResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OperatorLibraryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\"(\n\026OperatorLibraryRequest\022\016\n" +
      "\006column\030\001 \002(\t\")\n\027OperatorLibraryResponse" +
      "\022\016\n\006result\030\001 \003(\0012\210\003\n\026OperatorLibraryServ" +
      "ice\022=\n\010getGamma\022\027.OperatorLibraryRequest" +
      "\032\030.OperatorLibraryResponse\022;\n\006getErf\022\027.O" +
      "peratorLibraryRequest\032\030.OperatorLibraryR" +
      "esponse\022;\n\006getSum\022\027.OperatorLibraryReque" +
      "st\032\030.OperatorLibraryResponse\022;\n\006getAve\022\027" +
      ".OperatorLibraryRequest\032\030.OperatorLibrar" +
      "yResponse\022;\n\006getMax\022\027.OperatorLibraryReq",
      "uest\032\030.OperatorLibraryResponse\022;\n\006getMin" +
      "\022\027.OperatorLibraryRequest\032\030.OperatorLibr" +
      "aryResponseB\'\n\017org.osv.eventdbB\017Operator" +
      "LibraryH\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_OperatorLibraryRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_OperatorLibraryRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OperatorLibraryRequest_descriptor,
              new java.lang.String[] { "Column", });
          internal_static_OperatorLibraryResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_OperatorLibraryResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OperatorLibraryResponse_descriptor,
              new java.lang.String[] { "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
